### PR TITLE
Transfer fee fixes for new sv ui [ci]

### LINKED ISSUE #2794: Investigate what changes are required for transferFee changes in new UI

### PR DESCRIPTION
**Pull request by fayi-da**
This makes viewing amulet config changes cleaner(no extra fields for transfer fees on each proposal) until the fees have been removed in the cluster/network.

- omit transfer fee block if the fee is 0.0
- transferPreapproval should be `null`, not `''` when unset

Fixes #2794

Before
Screenshot 2025-11-19 at 13 09 22

After
Screenshot 2025-11-19 at 13 09 33

#### Cluster Testing
- [ ] If a cluster test is required, comment `/cluster_test` on this PR to request it, and ping someone with access to the DA-internal system to approve it.
- [ ] If a hard-migration test is required (from the latest release), comment `/hdm_test` on this PR to request it, and ping someone with access to the DA-internal system to approve it.

#### PR Guidelines
- [ ] Include any change that might be observable by our partners or affect their deployment in the [release notes](https://github.com/hyperledger-labs/splice/blob/main/docs/src/release_notes.rst).
- [ ] Specify fixed issues with `Fixes #n`, and mention issues worked on using `#n`
- [ ] Include a screenshot for frontend-related PRs - see [README](https://github.com/hyperledger-labs/splice/blob/main/TESTING.md#running-and-debugging-integration-tests) or use your favorite screenshot tool

#### Merge Guidelines
- [ ] Make the git commit message look sensible when squash-merging on GitHub (most likely: just copy your PR description).

### CODE REVIEW

File: apps/sv/frontend/src/utils/buildAmuletConfigChanges.ts [hunk 1]
```diff
@@ -156,6 +156,9 @@ function buildTransferFeeStepsChanges(
       ?.map((b, i) => {
         const idx = i + 1;
         const a = after?.[idx];
+
+        if (b._2 === '0.0') return [];
```
Comment (OriolMunoz-da) [inline apps/sv/frontend/src/utils/buildAmuletConfigChanges.ts:160]: I don't understand: why does this condition need to be copied here? Somehow the JSON diff is doing the right thing (does it have the same thing copied over?)

Comment (fayi-da) [reply apps/sv/frontend/src/utils/buildAmuletConfigChanges.ts:160]: It's for the logic that computes that `before -> after` view which is new in this UI

Comment (OriolMunoz-da) [reply apps/sv/frontend/src/utils/buildAmuletConfigChanges.ts:160]: ...and the json diff just gets HTML out of jsondiffpatch which is why it doesn't have the duplicate condition
wfm
