### PR TITLE
[ci] Fix for domainId getting truncated in http response.

### LINKED ISSUE #2764: SynchronizerId is not encoded correctly in http response in /v0/events and /v0/events/<update_id> API
In Json response domain shows as
`"domain_id": "global-domain::1220be58c29e...",`

Instead of the full domain_id, because `toString` is used instead of `encode`.

### PR DESCRIPTION
**Pull request by ray-roestenburg-da**
Fixes #2764 

#### Cluster Testing
- [ ] If a cluster test is required, comment `/cluster_test` on this PR to request it, and ping someone with access to the DA-internal system to approve it.
- [ ] If a hard-migration test is required (from the latest release), comment `/hdm_test` on this PR to request it, and ping someone with access to the DA-internal system to approve it.

#### PR Guidelines
- [ ] Include any change that might be observable by our partners or affect their deployment in the [release notes](https://github.com/hyperledger-labs/splice/blob/main/docs/src/release_notes.rst).
- [ ] Specify fixed issues with `Fixes #n`, and mention issues worked on using `#n`
- [ ] Include a screenshot for frontend-related PRs - see [README](https://github.com/hyperledger-labs/splice/blob/main/TESTING.md#running-and-debugging-integration-tests) or use your favorite screenshot tool

#### Merge Guidelines
- [ ] Make the git commit message look sensible when squash-merging on GitHub (most likely: just copy your PR description).

### CODE REVIEW

File: apps/scan/src/main/scala/org/lfdecentralizedtrust/splice/scan/admin/http/ScanHttpEncodings.scala [hunk 1]
```diff
@@ -489,7 +488,7 @@ object ScanHttpEncodings {
     httpApi.EventHistoryVerdict(
       updateId = verdict.updateId,
       migrationId = verdict.migrationId,
-      domainId = verdict.domainId.toString(),
+      domainId = Codec.encode(verdict.domainId),
```
Comment (ray-roestenburg-da) [inline apps/scan/src/main/scala/org/lfdecentralizedtrust/splice/scan/admin/http/ScanHttpEncodings.scala:491]: FYI @dfordivam we use this quite often in the http APIs to ensure we get correct output. We somehow missed that you were not using it

**Review by OriolMunoz-da — APPROVED** [review]
